version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: riksutin_dev
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./:/opt/app-root/src
    ports:
      - 3000:3000
      - 8000:8000
    container_name: riksutin_dev

  db:
    image: postgres:15.1
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/data
    container_name: riksutin_db

volumes:
  pg_data:
