name: E2E Tests

on: [workflow_call]

jobs:

  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Start the application
      run: docker-compose -f docker-compose.ci.yml up -d

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      env:
        CI: true
      run: npx playwright test

    - name: Print logs on failure
      shell: bash
      if: failure()
      run: docker-compose -f compose.ci.yml logs

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
